apiVersion: v1
kind: Secret
metadata:
  name: gitlab-registry-key
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "registry.minikube.local": {
          "username": "{{ .Values.registry.username }}",
          "password": "{{ .Values.registry.password }}",
          "auth": "{{ printf "%s:%s" .Values.registry.username .Values.registry.password | b64enc }}"
        }
      }
    }
