apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: web-app-project
  namespace: argocd
spec:
  description: Project for Web Application
  sourceRepos:
    - "*"
  destinations:
    - namespace: app
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
