registry:
  username: "gitlab+deploy-token-1"
  password: "gldt-RwwBNAkFwy7zDQRXCsvx"

image:
  repository: registry.minikube.local/rymond044/final_k8s_app_repo
  tag: "dev-v2.2.1"
  pullPolicy: IfNotPresent

secret:
  appSecretValue: "super-secret-turbo-pro-dolbit-digital-data"

resources:
  app:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 150m
      memory: 128Mi
  nginx:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 64Mi

ingress:
  enabled: true
  host: app.minikube.local
